version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: reqti_app
    restart: always
    volumes:
      - .:/var/www/html
    environment:
      # Variables para tu Proxy Inverso
      - VIRTUAL_HOST=reqti.dpmc.cl
      - LETSENCRYPT_HOST=reqti.dpmc.cl
    networks:
      - red_produccion

networks:
  red_produccion:
    external: true